baseurl: ""
markdown: kramdown
theme: minima
plugins: []
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - faviconData.json
  - package.json
  - yarn.lock
  - README.md
  - '*.orig'
  - '*.log'
  - install-dependencies.sh

include:
  - .nojekyll

permalink: /blog/:categories/:title/
categories: []
