version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    parallelism: 1

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-
            - v1-gem-cache-{{ arch }}-
      - run:
          name: Configure Bundler
          command: |
            BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")
            echo "export BUNDLER_VERSION=$BUNDLER_VERSION" >> $BASH_ENV
            source $BASH_ENV
            gem install bundler -v $BUNDLER_VERSION
      - run: bundle install --path ~/.bundle && bundle clean
      - save_cache:
          paths:
            - ~/.bundle
          key: v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Configure Node
          command: |
            set +e
            touch $BASH_ENV
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo 'nvm install v8.16.0' >> $BASH_ENV
            echo 'nvm alias default v8.16.0' >> $BASH_ENV
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      # - run: yarn test
      - run: ./deploy.sh


workflows:
  version: 2
  commit:
    jobs:
     - build:
        filters:
          branches:
            ignore: gh-pages
